export const REQUEST_GET_OBJECTS = "REQUEST_GET_OBJECTS";
export const REQUEST_ADD_OBJECT = "REQUEST_ADD_OBJECT";
export const REQUEST_DELETE_OBJECT = "REQUEST_DELETE_OBJECT";
export const REQUEST_EDITED_OBJECT = "REQUEST_EDITED_OBJECT";