export const OBJECT_POPUP_IS_VISIBLE = "OBJECT_POPUP_IS_VISIBLE";
export const OBJECT_POPUP_IS_NOT_VISIBLE = "OBJECT_POPUP_IS_NOT_VISIBLE";

export const OBJECT_POPUP_NEW_OBJECT = "OBJECT_POPUP_NEW_OBJECT";

export const OBJECT_POPUP_AWAIT_REQUEST = "OBJECT_POPUP_AWAIT_REQUEST";
export const OBJECT_POPUP_ERROR_REQUEST = "OBJECT_POPUP_ERROR_REQUEST";
export const OBJECT_POPUP_SUCCESS_REQUEST = "OBJECT_POPUP_SUCCESS_REQUEST";